<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

/**
 * Author = provider user (ids 2-11). blogs.service_sub_category_id is NOT NULL so categories 8-10 fall back to valid sub-categories.
 */
class BlogsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $rows = [
            [
                'id' => 1,
                'title' => '5 Tips to Keep Your Protective Styles Fresh',
                'slug' => '5-tips-keep-protective-styles-fresh',
                'user_id' => 2,
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'image' => 'uploads/blogs/5-tips-keep-protective-styles-fresh.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/5-tips-keep-protective-styles-fresh.jpg',
                'content' => '<p>5 Tips to Keep Your Protective Styles Fresh - practical advice from our verified braids professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 120,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now()->subDays(30),
                'featured' => 1,
            ],
            [
                'id' => 2,
                'title' => 'How to Choose the Right Haircut for Your Face Shape',
                'slug' => 'choose-right-haircut-face-shape',
                'user_id' => 2,
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'image' => 'uploads/blogs/choose-right-haircut-face-shape.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/choose-right-haircut-face-shape.jpg',
                'content' => '<p>How to Choose the Right Haircut for Your Face Shape - practical advice from our verified hair professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 157,
                'created_at' => Carbon::now()->subDays(28),
                'updated_at' => Carbon::now()->subDays(28),
                'featured' => 1,
            ],
            [
                'id' => 3,
                'title' => 'Barbershop Etiquette: What to Ask Before Your Fade',
                'slug' => 'barbershop-etiquette-fade',
                'user_id' => 4,
                'service_category_id' => 3,
                'service_sub_category_id' => 5,
                'image' => 'uploads/blogs/barbershop-etiquette-fade.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/barbershop-etiquette-fade.jpg',
                'content' => '<p>Barbershop Etiquette: What to Ask Before Your Fade - practical advice from our verified barbershop professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 194,
                'created_at' => Carbon::now()->subDays(26),
                'updated_at' => Carbon::now()->subDays(26),
                'featured' => 1,
            ],
            [
                'id' => 4,
                'title' => 'Making Your Gel Manicure Last Longer',
                'slug' => 'making-gel-manicure-last-longer',
                'user_id' => 5,
                'service_category_id' => 4,
                'service_sub_category_id' => 6,
                'image' => 'uploads/blogs/making-gel-manicure-last-longer.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/making-gel-manicure-last-longer.jpg',
                'content' => '<p>Making Your Gel Manicure Last Longer - practical advice from our verified nails professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 231,
                'created_at' => Carbon::now()->subDays(24),
                'updated_at' => Carbon::now()->subDays(24),
                'featured' => 0,
            ],
            [
                'id' => 5,
                'title' => 'Bridal Makeup Timeline: When to Book and Trial',
                'slug' => 'bridal-makeup-timeline',
                'user_id' => 6,
                'service_category_id' => 5,
                'service_sub_category_id' => 8,
                'image' => 'uploads/blogs/bridal-makeup-timeline.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/bridal-makeup-timeline.jpg',
                'content' => '<p>Bridal Makeup Timeline: When to Book and Trial - practical advice from our verified makeup professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 268,
                'created_at' => Carbon::now()->subDays(22),
                'updated_at' => Carbon::now()->subDays(22),
                'featured' => 0,
            ],
            [
                'id' => 6,
                'title' => 'A Simple Skincare Routine for Kigali\'s Climate',
                'slug' => 'simple-skincare-routine-kigali',
                'user_id' => 7,
                'service_category_id' => 6,
                'service_sub_category_id' => 9,
                'image' => 'uploads/blogs/simple-skincare-routine-kigali.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/simple-skincare-routine-kigali.jpg',
                'content' => '<p>A Simple Skincare Routine for Kigali\'s Climate - practical advice from our verified skincare professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 305,
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now()->subDays(20),
                'featured' => 0,
            ],
            [
                'id' => 7,
                'title' => 'What to Expect at Your First Massage',
                'slug' => 'what-to-expect-first-massage',
                'user_id' => 8,
                'service_category_id' => 7,
                'service_sub_category_id' => 10,
                'image' => 'uploads/blogs/what-to-expect-first-massage.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/what-to-expect-first-massage.jpg',
                'content' => '<p>What to Expect at Your First Massage - practical advice from our verified spa professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 342,
                'created_at' => Carbon::now()->subDays(18),
                'updated_at' => Carbon::now()->subDays(18),
                'featured' => 0,
            ],
            [
                'id' => 8,
                'title' => 'Waxing 101: Prep and Aftercare',
                'slug' => 'waxing-101-prep-aftercare',
                'user_id' => 9,
                'service_category_id' => 8,
                'service_sub_category_id' => 5,
                'image' => 'uploads/blogs/waxing-101-prep-aftercare.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/waxing-101-prep-aftercare.jpg',
                'content' => '<p>Waxing 101: Prep and Aftercare - practical advice from our verified waxing professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 379,
                'created_at' => Carbon::now()->subDays(16),
                'updated_at' => Carbon::now()->subDays(16),
                'featured' => 0,
            ],
            [
                'id' => 9,
                'title' => 'Planning Your Wedding-Day Beauty Schedule',
                'slug' => 'wedding-day-beauty-schedule',
                'user_id' => 10,
                'service_category_id' => 9,
                'service_sub_category_id' => 8,
                'image' => 'uploads/blogs/wedding-day-beauty-schedule.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/wedding-day-beauty-schedule.jpg',
                'content' => '<p>Planning Your Wedding-Day Beauty Schedule - practical advice from our verified bridal professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'published',
                'views' => 416,
                'created_at' => Carbon::now()->subDays(14),
                'updated_at' => Carbon::now()->subDays(14),
                'featured' => 0,
            ],
            [
                'id' => 10,
                'title' => 'Lash Extensions: Care Tips to Make Them Last',
                'slug' => 'lash-extensions-care-tips',
                'user_id' => 11,
                'service_category_id' => 10,
                'service_sub_category_id' => 9,
                'image' => 'uploads/blogs/lash-extensions-care-tips.jpg',
                'thumbnail' => 'uploads/blogs/thumbs/lash-extensions-care-tips.jpg',
                'content' => '<p>Lash Extensions: Care Tips to Make Them Last - practical advice from our verified lashes professionals in Kigali.</p><p>Book a trusted provider on the platform to put these tips into practice.</p>',
                'status' => 'draft',
                'views' => 453,
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => Carbon::now()->subDays(12),
                'featured' => 0,
            ],
        ];

        // insertOrIgnore => safe to re-run (explicit ids, duplicates are skipped)
        DB::table('blogs')->insertOrIgnore($rows);
    }
}
