<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

/**
 * Customer i (user 22+i-1) books service i with staff i. Totals are RWF after discount.
 */
class ServiceBookingsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $rows = [
            [
                'id' => 1,
                'user_id' => 22,
                'status' => 'completed',
                'service_id' => 1,
                'total' => 10800,
                'payment_mode' => 'MTN MoMo',
                'names' => 'Kevine Ishimwe',
                'email' => 'kevine.ishimwe@example.com',
                'phone' => '+250789110200',
                'location' => 'Kimironko, Kigali',
                'notes' => 'Please use a light-hold finish.',
                'date' => Carbon::now()->addDays(-14)->format('Y-m-d'),
                'time' => '10:00',
                'staff_id' => 1,
                'payment_status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'user_id' => 23,
                'status' => 'approved',
                'service_id' => 2,
                'total' => 40000,
                'payment_mode' => 'Airtel Money',
                'names' => 'Yvonne Uwineza',
                'email' => 'yvonne.uwineza@example.com',
                'phone' => '+250789110201',
                'location' => 'Remera, Kigali',
                'notes' => 'Bring my own extension hair.',
                'date' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'time' => '09:30',
                'staff_id' => 2,
                'payment_status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'user_id' => 24,
                'status' => 'completed',
                'service_id' => 3,
                'total' => 6000,
                'payment_mode' => 'Cash',
                'names' => 'Didier Nshimiyimana',
                'email' => 'didier.nshimiyimana@example.com',
                'phone' => '+250789110202',
                'location' => 'Kicukiro, Kigali',
                'notes' => 'Short on the sides, longer on top.',
                'date' => Carbon::now()->addDays(-9)->format('Y-m-d'),
                'time' => '14:00',
                'staff_id' => 3,
                'payment_status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'user_id' => 25,
                'status' => 'pending',
                'service_id' => 4,
                'total' => 13000,
                'payment_mode' => 'MTN MoMo',
                'names' => 'Bella Kamikazi',
                'email' => 'bella.kamikazi@example.com',
                'phone' => '+250789110203',
                'location' => 'Nyarutarama, Kigali',
                'notes' => 'Pastel pink, please.',
                'date' => Carbon::now()->addDays(5)->format('Y-m-d'),
                'time' => '11:00',
                'staff_id' => 4,
                'payment_status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'user_id' => 26,
                'status' => 'approved',
                'service_id' => 5,
                'total' => 60000,
                'payment_mode' => 'Card',
                'names' => 'Christian Mugisha',
                'email' => 'christian.mugisha@example.com',
                'phone' => '+250789110204',
                'location' => 'Kacyiru, Kigali',
                'notes' => 'Wedding on Saturday, need a natural glam.',
                'date' => Carbon::now()->addDays(12)->format('Y-m-d'),
                'time' => '08:00',
                'staff_id' => 5,
                'payment_status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'user_id' => 27,
                'status' => 'completed',
                'service_id' => 6,
                'total' => 29750,
                'payment_mode' => 'MTN MoMo',
                'names' => 'Alice Mutesi',
                'email' => 'alice.mutesi@example.com',
                'phone' => '+250789110205',
                'location' => 'Kibagabaga, Kigali',
                'notes' => 'Sensitive skin, avoid fragrance.',
                'date' => Carbon::now()->addDays(-6)->format('Y-m-d'),
                'time' => '15:30',
                'staff_id' => 6,
                'payment_status' => 'paid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'user_id' => 28,
                'status' => 'canceled',
                'service_id' => 7,
                'total' => 40000,
                'payment_mode' => 'Cash',
                'names' => 'Joseph Kagabo',
                'email' => 'joseph.kagabo@example.com',
                'phone' => '+250789110206',
                'location' => 'Nyamirambo, Kigali',
                'notes' => 'Prefer a quiet room.',
                'date' => Carbon::now()->addDays(2)->format('Y-m-d'),
                'time' => '13:00',
                'staff_id' => 7,
                'payment_status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'user_id' => 29,
                'status' => 'rescheduled',
                'service_id' => 8,
                'total' => 25000,
                'payment_mode' => 'Airtel Money',
                'names' => 'Nadine Uwitonze',
                'email' => 'nadine.uwitonze@example.com',
                'phone' => '+250789110207',
                'location' => 'Gikondo, Kigali',
                'notes' => 'First time waxing.',
                'date' => Carbon::now()->addDays(8)->format('Y-m-d'),
                'time' => '16:00',
                'staff_id' => 8,
                'payment_status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'user_id' => 30,
                'status' => 'pending',
                'service_id' => 9,
                'total' => 130000,
                'payment_mode' => 'Card',
                'names' => 'Prince Rukundo',
                'email' => 'prince.rukundo@example.com',
                'phone' => '+250789110208',
                'location' => 'Gisozi, Kigali',
                'notes' => 'Trial session first, please.',
                'date' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'time' => '07:00',
                'staff_id' => 9,
                'payment_status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'user_id' => 31,
                'status' => 'decline',
                'service_id' => 10,
                'total' => 30000,
                'payment_mode' => 'MTN MoMo',
                'names' => 'Elyse Umuhoza',
                'email' => 'elyse.umuhoza@example.com',
                'phone' => '+250789110209',
                'location' => 'Kanombe, Kigali',
                'notes' => 'Allergic to latex adhesive.',
                'date' => Carbon::now()->addDays(4)->format('Y-m-d'),
                'time' => '12:30',
                'staff_id' => 10,
                'payment_status' => 'unpaid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // insertOrIgnore => safe to re-run (explicit ids, duplicates are skipped)
        DB::table('service_bookings')->insertOrIgnore($rows);
    }
}
