<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $rows = [
            [
                'id' => 1,
                'name' => 'Signature Cut & Blow-dry',
                'slug' => 'signature-cut-blow-dry',
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'service_provider_id' => 1,
                'price' => 12000,
                'discount' => 10,
                'discount_type' => 'percent',
                'image' => 'uploads/services/signature-cut-blow-dry.jpg',
                'description' => 'A consultation, precision cut, wash and salon-finish blow-dry tailored to your hair type.',
                'inclusion' => 'Consultation, Shampoo & conditioning, Cut, Blow-dry',
                'exclusion' => 'Colour, Deep treatments',
                'duration' => '60 minutes',
                'status' => 1,
                'featured' => 1,
                'location' => 'Kimironko, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Knotless Box Braids',
                'slug' => 'knotless-box-braids',
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'service_provider_id' => 2,
                'price' => 40000,
                'discount' => null,
                'discount_type' => null,
                'image' => 'uploads/services/knotless-box-braids.jpg',
                'description' => 'Lightweight, pain-free knotless braids in your choice of size and length.',
                'inclusion' => 'Wash & detangle, Braiding, Edge styling, Braid hair included',
                'exclusion' => 'Extra-long lengths, Curls at ends',
                'duration' => '5 hours',
                'status' => 1,
                'featured' => 1,
                'location' => 'Remera, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Classic Fade & Beard Trim',
                'slug' => 'classic-fade-beard-trim',
                'service_category_id' => 3,
                'service_sub_category_id' => 5,
                'service_provider_id' => 3,
                'price' => 6000,
                'discount' => null,
                'discount_type' => null,
                'image' => 'uploads/services/classic-fade-beard-trim.jpg',
                'description' => 'Clean fade with line-up and a shaped beard trim finished with hot towel.',
                'inclusion' => 'Fade cut, Line-up, Beard trim, Hot towel',
                'exclusion' => 'Hair colouring',
                'duration' => '45 minutes',
                'status' => 1,
                'featured' => 0,
                'location' => 'Kicukiro, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Gel Manicure',
                'slug' => 'gel-manicure',
                'service_category_id' => 4,
                'service_sub_category_id' => 6,
                'service_provider_id' => 4,
                'price' => 15000,
                'discount' => 2000,
                'discount_type' => 'fixed',
                'image' => 'uploads/services/gel-manicure.jpg',
                'description' => 'Nail shaping, cuticle care and long-lasting gel polish in your favourite shade.',
                'inclusion' => 'Nail shaping, Cuticle care, Hand massage, Gel polish',
                'exclusion' => 'Nail art, Extensions',
                'duration' => '60 minutes',
                'status' => 1,
                'featured' => 1,
                'location' => 'Nyarutarama, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Bridal & Event Makeup',
                'slug' => 'bridal-event-makeup',
                'service_category_id' => 5,
                'service_sub_category_id' => 8,
                'service_provider_id' => 5,
                'price' => 60000,
                'discount' => null,
                'discount_type' => null,
                'image' => 'uploads/services/bridal-event-makeup.jpg',
                'description' => 'Full-glam makeup for weddings and events with skin prep and lashes included.',
                'inclusion' => 'Skin prep, Full-face makeup, Lashes, Touch-up kit',
                'exclusion' => 'Hair styling, Travel outside Kigali',
                'duration' => '2 hours',
                'status' => 1,
                'featured' => 1,
                'location' => 'Kacyiru, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Deep Cleansing Facial',
                'slug' => 'deep-cleansing-facial',
                'service_category_id' => 6,
                'service_sub_category_id' => 9,
                'service_provider_id' => 6,
                'price' => 35000,
                'discount' => 15,
                'discount_type' => 'percent',
                'image' => 'uploads/services/deep-cleansing-facial.jpg',
                'description' => 'Steam, extraction, exfoliation and a hydrating mask to reset tired or congested skin.',
                'inclusion' => 'Skin analysis, Cleanse & steam, Extraction, Mask',
                'exclusion' => 'Chemical peels',
                'duration' => '75 minutes',
                'status' => 1,
                'featured' => 0,
                'location' => 'Kibagabaga, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Full Body Relaxation Massage',
                'slug' => 'full-body-relaxation-massage',
                'service_category_id' => 7,
                'service_sub_category_id' => 10,
                'service_provider_id' => 7,
                'price' => 40000,
                'discount' => null,
                'discount_type' => null,
                'image' => 'uploads/services/full-body-relaxation-massage.jpg',
                'description' => 'A soothing full-body massage with warm oils to relieve stress and muscle tension.',
                'inclusion' => 'Consultation, 60-minute massage, Aromatherapy oils, Herbal tea',
                'exclusion' => 'Hot stone add-on',
                'duration' => '60 minutes',
                'status' => 1,
                'featured' => 1,
                'location' => 'Nyamirambo, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Full Body Waxing',
                'slug' => 'full-body-waxing',
                'service_category_id' => 8,
                'service_sub_category_id' => null,
                'service_provider_id' => 8,
                'price' => 25000,
                'discount' => null,
                'discount_type' => null,
                'image' => 'uploads/services/full-body-waxing.jpg',
                'description' => 'Gentle full-body hair removal using skin-friendly wax and single-use applicators.',
                'inclusion' => 'Skin prep, Waxing, Soothing aftercare',
                'exclusion' => 'Intimate areas',
                'duration' => '90 minutes',
                'status' => 1,
                'featured' => 0,
                'location' => 'Gikondo, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Bridal Hair & Makeup Package',
                'slug' => 'bridal-hair-makeup-package',
                'service_category_id' => 9,
                'service_sub_category_id' => null,
                'service_provider_id' => 9,
                'price' => 150000,
                'discount' => 20000,
                'discount_type' => 'fixed',
                'image' => 'uploads/services/bridal-hair-makeup-package.jpg',
                'description' => 'Complete bridal hair and makeup with a trial session and day-of touch-ups.',
                'inclusion' => 'Trial session, Bridal hair, Bridal makeup, Touch-up kit',
                'exclusion' => 'Bridesmaid styling',
                'duration' => '4 hours',
                'status' => 1,
                'featured' => 1,
                'location' => 'Gisozi, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Classic Lash Extensions',
                'slug' => 'classic-lash-extensions',
                'service_category_id' => 10,
                'service_sub_category_id' => null,
                'service_provider_id' => 10,
                'price' => 30000,
                'discount' => null,
                'discount_type' => null,
                'image' => 'uploads/services/classic-lash-extensions.jpg',
                'description' => 'A natural-looking classic lash set applied one-to-one for a soft, defined eye.',
                'inclusion' => 'Patch test, Full classic set, Aftercare guide',
                'exclusion' => 'Lash removal, Volume sets',
                'duration' => '2 hours',
                'status' => 1,
                'featured' => 0,
                'location' => 'Kanombe, Kigali',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // insertOrIgnore => safe to re-run (explicit ids, duplicates are skipped)
        DB::table('services')->insertOrIgnore($rows);
    }
}
