<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Hash;

/**
 * 1 admin (ADM) + 10 providers (SVP, ids 2-11) + 10 staff (STF, ids 12-21) + 10 customers (CST, ids 22-31).
 * Default password for all accounts: password
 */
class UsersSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $password = Hash::make('password'); // default password for every seeded account: password

        $rows = [
            [
                'id' => 1,
                'name' => 'Platform Admin',
                'email' => 'admin@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'ADM',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Grace Uwase',
                'email' => 'grace.uwase@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Diane Mukamana',
                'email' => 'diane.mukamana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Jean Claude Habimana',
                'email' => 'jean.claude.habimana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Sandrine Ingabire',
                'email' => 'sandrine.ingabire@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Aline Umutoni',
                'email' => 'aline.umutoni@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Claudine Mukeshimana',
                'email' => 'claudine.mukeshimana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Patience Kayitesi',
                'email' => 'patience.kayitesi@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Solange Uwimana',
                'email' => 'solange.uwimana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Marie Rose Niyonsenga',
                'email' => 'marie.rose.niyonsenga@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'Belyse Iradukunda',
                'email' => 'belyse.iradukunda@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'SVP',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'Olivier Nsengiyumva',
                'email' => 'olivier.nsengiyumva@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'Chantal Uwera',
                'email' => 'chantal.uwera@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Fabrice Ndayisaba',
                'email' => 'fabrice.ndayisaba@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'Jeanne Mukamazimpaka',
                'email' => 'jeanne.mukamazimpaka@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'Innocent Bizimana',
                'email' => 'innocent.bizimana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'Josiane Nyirahabimana',
                'email' => 'josiane.nyirahabimana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'Emmanuel Tuyisenge',
                'email' => 'emmanuel.tuyisenge@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'Vestine Mukandayisenga',
                'email' => 'vestine.mukandayisenga@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'name' => 'Patrick Munyaneza',
                'email' => 'patrick.munyaneza@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'name' => 'Liliane Uwamahoro',
                'email' => 'liliane.uwamahoro@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'STF',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Kevine Ishimwe',
                'email' => 'kevine.ishimwe@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Yvonne Uwineza',
                'email' => 'yvonne.uwineza@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'Didier Nshimiyimana',
                'email' => 'didier.nshimiyimana@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'Bella Kamikazi',
                'email' => 'bella.kamikazi@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Christian Mugisha',
                'email' => 'christian.mugisha@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'name' => 'Alice Mutesi',
                'email' => 'alice.mutesi@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Joseph Kagabo',
                'email' => 'joseph.kagabo@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'Nadine Uwitonze',
                'email' => 'nadine.uwitonze@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'Prince Rukundo',
                'email' => 'prince.rukundo@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'Elyse Umuhoza',
                'email' => 'elyse.umuhoza@example.com',
                'email_verified_at' => $now,
                'password' => $password,
                'remember_token' => null,
                'current_team_id' => null,
                'profile_photo_path' => null,
                'utype' => 'CST',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // insertOrIgnore => safe to re-run (explicit ids, duplicates are skipped)
        DB::table('users')->insertOrIgnore($rows);
    }
}
